server:
	arm-linux-gnueabihf-gcc -o arm_main main.c Data_Delivery_Cloud.c LEDDisplayNetworkPortModule.c Reteiever_Processing.c Retriever_collection.c ReuseFunction.c Watchdog.c -L. libcurl.a libsqlite3.so.0.8.6 -pthread -lrt
